target: 'validation'
prediction:
  click:
    covisitation_target:
      setting0:
        top: 20
      setting1:
        top: 20
    covisitation_mix: 'mix0'
  carts:
    covisitation_target:
      setting0:
        top: 20
      setting1:
        top: 20
    covisitation_mix: 'mix0'
  orders:
    covisitation_target:
      setting0:
        top: 20
      setting1:
        top: 20
    covisitation_mix: 'mix0'

covisitation:
  - 'setting0'
  - 'setting2'
