# 全体
target: 'validation' # target or configuration
prediction:
  click:
    covisitation:
      target:
        - setting0
        - setting1
      ensemble: 'ensemble0'
  carts:
    covisitation:
      target:
        - setting0
        - setting1
      ensemble: 'ensemble0'
  orders:
    covisitation:
      target:
        - setting0
        - setting1
      ensemble: 'ensemble0'

# co-visitation matrix
# setting{N}はoutputと紐づける
# なので上書きしたりしない
covisitation:
  setting0:
    name: 'type_weight' # co-visitationの種類
    N: 60 # 上位Nのaidを取得
    type_weight: # typeごとの重みづけ
      0: 1
      1: 6
      2: 3
  setting1:
    name: 'buy2buy'
    N: 60
  setting2:
    name: 'time_weight' # co-visitationの種類
    N: 60 # 上位Nのaidを取得
